language: python
python:
- 3.7
install:
- pip install -r requirements.txt
script:
- pytest tests.py
deploy:
  provider: heroku
  api_key:
    secure: df3affcd-1e1b-4a34-8afb-a014aa1e4459
  app: tinyhitslyricbot
